export const employees = [
    {
      id: 1,
      name: "Arjun Kumar",
      email: "arjun.kumar@company.com",
      department: "Engineering",
      role: "Frontend Developer",
    },
    {
      id: 2,
      name: "Arjun Reddy",
      email: "arjun.reddy@company.com",
      department: "Engineering",
      role: "Backend Developer",
    },
    {
      id: 3,
      name: "Priya Sharma",
      email: "priya.sharma@company.com",
      department: "HR",
      role: "HR Manager",
    },
    {
      id: 4,
      name: "Rahul Verma",
      email: "rahul.verma@company.com",
      department: "Sales",
      role: "Sales Executive",
    },
    {
      id: 5,
      name: "Sneha Iyer",
      email: "sneha.iyer@company.com",
      department: "Engineering",
      role: "QA Engineer",
    },
    {
      id: 6,
      name: "Karthik Raj",
      email: "karthik.raj@company.com",
      department: "Engineering",
      role: "DevOps Engineer",
    },
    {
      id: 7,
      name: "Anjali Mehta",
      email: "anjali.mehta@company.com",
      department: "Marketing",
      role: "Content Strategist",
    },
    {
      id: 8,
      name: "Vikram Singh",
      email: "vikram.singh@company.com",
      department: "Engineering",
      role: "Tech Lead",
    },
    {
      id: 9,
      name: "Arun Kumar",
      email: "arun.kumar@company.com",
      department: "Finance",
      role: "Accountant",
    },
    {
      id: 10,
      name: "Priyanka Das",
      email: "priyanka.das@company.com",
      department: "HR",
      role: "Recruiter",
    },
    {
      id: 11,
      name: "Rahul Nair",
      email: "rahul.nair@company.com",
      department: "Support",
      role: "Customer Support",
    },
    {
      id: 12,
      name: "SNEHA REDDY",
      email: "sneha.reddy@company.com",
      department: "Engineering",
      role: "Frontend Developer",
    },
  ];